services:
  backend-api:
    container_name: taller-api-container
    build:
      context: ./Taller_Challenge_Backend/Taller_Challenge_Backend.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  pricing-service:
    container_name: taller-pricing-container
    build:
      context: ./Taller_Challenge_Backend/Taller_Challenge_Backend.API
      dockerfile: Taller_Challenge_Backend.Pricing/Dockerfile
    ports:
      - "5050:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taller-sql-container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=4Hg2wHX6Ncd6bUJ
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "4Hg2wHX6Ncd6bUJ", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  frontend:
    container_name: taller-frontend-container
    build: 
      context: ./Taller_Challenge_FrontEnd/Taller_Challenge_FrontEnd
      dockerfile: Dockerfile
    ports:
      - "4205:80"
    depends_on:
      - backend-api
      - pricing-service